import pandas as pd
import json


def CARREGAR_RELATORIO_DETALHE():


    PERIODO_VIGENTE   = pd.read_csv("previsao_trens/src/PARAMETROS/PERIODO_VIGENTE.csv",   encoding='utf-8-sig', sep=';', index_col=0)
    TERMINAIS_ATIVOS  = pd.read_csv("previsao_trens/src/PARAMETROS/DESCARGAS_ATIVAS.csv",  encoding='utf-8-sig', sep=';', index_col=0)
    lst_TERMINAIS_ATIVOS  = TERMINAIS_ATIVOS[TERMINAIS_ATIVOS['TERMINAL'] > 0].index.tolist()
    TERMINAIS_ATIVOS.drop('TERMINAL', axis=1, inplace=True)    
    
    #ESTOU REMOVENDO O D-1 DO CÁLCULO PARA VER NO QUE VAI DAR
    PERIODO_VIGENTE = PERIODO_VIGENTE.drop(PERIODO_VIGENTE.index[0]) 
    LISTA_DATA_ARQ  = PERIODO_VIGENTE["DATA_ARQ"].tolist()
    
    RELATORIO_DETALHE = {}

    #OBTENDO OS VALORES DA DETALHADA
    for TERMINAL in lst_TERMINAIS_ATIVOS:  #CADA TERMINAL
        RELATORIO_DETALHE[TERMINAL] = {}
        #print(TERMINAL)

        DESCARGAS_ATIVAS = TERMINAIS_ATIVOS.loc[TERMINAL][TERMINAIS_ATIVOS.loc[TERMINAL] > 0].index.tolist()   

        for DESCARGAS in DESCARGAS_ATIVAS: #CADA DESCARGA
            
            FERROVIA, PRODUTO = DESCARGAS.split("_")
            #print(f"\t {FERROVIA, PRODUTO}")
            if not FERROVIA in RELATORIO_DETALHE[TERMINAL]:
                RELATORIO_DETALHE[TERMINAL][FERROVIA] = {}

            if not PRODUTO in RELATORIO_DETALHE[TERMINAL][FERROVIA]:   
                RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO] = {}

            for DIA_LOGISTICO, DATA_ARQ in enumerate(LISTA_DATA_ARQ): #CADA DIA
                
                RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO] = {}
                RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["RECEBIMENTOS"] = {}
                RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["PEDRA"] = {} 
                RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["SALDOS"] = {}
                
                with open(f"previsao_trens/src/DESCARGAS/{TERMINAL}/descarga_{DATA_ARQ}.json") as ARQUIVO_DESCARGA:
                    DESCARGA = json.load(ARQUIVO_DESCARGA)

                try: #['SALDO_DE_VIRADA_VAZIOS', 'SALDO_DE_VIRADA', 'PRODUTIVIDADE', 'RECEBIMENTOS', 'PEDRA']

                    RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["SALDOS"]["P1"] = DESCARGA["DESCARGAS"][FERROVIA][PRODUTO]["INDICADORES"]["SALDO_DE_VIRADA"]

                    RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["RECEBIMENTOS"]["P1"]  = DESCARGA["DESCARGAS"][FERROVIA][PRODUTO]["INDICADORES"]["RECEBIMENTOS"][0]
                    RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["RECEBIMENTOS"]["P2"]  = DESCARGA["DESCARGAS"][FERROVIA][PRODUTO]["INDICADORES"]["RECEBIMENTOS"][1]
                    RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["RECEBIMENTOS"]["P3"]  = DESCARGA["DESCARGAS"][FERROVIA][PRODUTO]["INDICADORES"]["RECEBIMENTOS"][2]
                    RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["RECEBIMENTOS"]["P4"]  = DESCARGA["DESCARGAS"][FERROVIA][PRODUTO]["INDICADORES"]["RECEBIMENTOS"][3]

                    RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["PEDRA"]["P1"] = DESCARGA["DESCARGAS"][FERROVIA][PRODUTO]["INDICADORES"]["PEDRA"][0]
                    RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["PEDRA"]["P2"] = DESCARGA["DESCARGAS"][FERROVIA][PRODUTO]["INDICADORES"]["PEDRA"][1]
                    RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["PEDRA"]["P3"] = DESCARGA["DESCARGAS"][FERROVIA][PRODUTO]["INDICADORES"]["PEDRA"][2]        
                    RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["PEDRA"]["P4"] = DESCARGA["DESCARGAS"][FERROVIA][PRODUTO]["INDICADORES"]["PEDRA"][3]

                    for i in range(2, 5):
                        
                        REC = RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["RECEBIMENTOS"][f"P{i-1}"]
                        PD  = RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["PEDRA"][f"P{i-1}"]
                        SD  = RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["SALDOS"][f"P{i-1}"] 

                        RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["SALDOS"][f"P{i}"] =    REC + SD - PD


                    TOTAL_PEDRA  = 0
                    TOTAL_OFERTA = 0

                    for i in range (1, 5):
                    

                        TOTAL_PEDRA  = TOTAL_PEDRA  + RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["PEDRA"][f"P{i}"]
                        TOTAL_OFERTA = TOTAL_OFERTA + RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["RECEBIMENTOS"][f"P{i}"]
                    

                    RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["TT_OF"] = TOTAL_OFERTA + RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["SALDOS"]["P1"]  
                    RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["TT_PD"] = TOTAL_PEDRA
    
                except: 
                        pass
    

    #AJUSTANDO OS TERMINAIS DE ACUCAR
    TERMINAIS_ACUCAR = []
    for TERMINAL in RELATORIO_DETALHE.keys():
        
        try:
            TERMINAL_ORIGINAL = TERMINAL.split(" ")[0]

            if TERMINAL.split(" ")[1] == "ACUCAR":
                TERMINAIS_ACUCAR.append(TERMINAL) 
                for FERROVIA in RELATORIO_DETALHE[TERMINAL]:

                    if not TERMINAL_ORIGINAL in RELATORIO_DETALHE:
                        RELATORIO_DETALHE[TERMINAL_ORIGINAL] = {}

                    if not FERROVIA in RELATORIO_DETALHE[TERMINAL_ORIGINAL]:
                        RELATORIO_DETALHE[TERMINAL_ORIGINAL][FERROVIA] = {} 

                    RELATORIO_DETALHE[TERMINAL_ORIGINAL][FERROVIA]["ACUCAR"] = RELATORIO_DETALHE[TERMINAL][FERROVIA]["ACUCAR"]    
        except:
            pass

    for TERMINAL in TERMINAIS_ACUCAR:

        del RELATORIO_DETALHE[TERMINAL]

    #print(f"ACUCAR AJUSTADO")
    for TERMINAL in RELATORIO_DETALHE.keys():
        
        #print(f"{TERMINAL}")
        RELATORIO_DETALHE[TERMINAL]["TOTAL"] = {}

        for FERROVIA in RELATORIO_DETALHE[TERMINAL]:
            
            #print(f"\t {FERROVIA}")
            if FERROVIA != "TOTAL":
                for PRODUTO in RELATORIO_DETALHE[TERMINAL][FERROVIA]:
                    #print(f"\t \t {PRODUTO}")
                    for DIA_LOGISTICO, DATA_ARQ in enumerate(LISTA_DATA_ARQ):


                        if not DIA_LOGISTICO in RELATORIO_DETALHE[TERMINAL]["TOTAL"]:
                            RELATORIO_DETALHE[TERMINAL]["TOTAL"][DIA_LOGISTICO] = {}

                        COLUNAS = ["SALDOS", "RECEBIMENTOS", "PEDRA"]
                        
                        for COLUNA in COLUNAS:
                            
                            if not COLUNA in RELATORIO_DETALHE[TERMINAL]["TOTAL"][DIA_LOGISTICO]:
                                RELATORIO_DETALHE[TERMINAL]["TOTAL"][DIA_LOGISTICO][COLUNA] = {"P1": 0, "P2": 0, "P3": 0, "P4": 0}
                            
                            RELATORIO_DETALHE[TERMINAL]["TOTAL"][DIA_LOGISTICO][COLUNA]["P1"] += RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO][COLUNA]["P1"]
                            RELATORIO_DETALHE[TERMINAL]["TOTAL"][DIA_LOGISTICO][COLUNA]["P2"] += RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO][COLUNA]["P2"]
                            RELATORIO_DETALHE[TERMINAL]["TOTAL"][DIA_LOGISTICO][COLUNA]["P3"] += RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO][COLUNA]["P3"]
                            RELATORIO_DETALHE[TERMINAL]["TOTAL"][DIA_LOGISTICO][COLUNA]["P4"] += RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO][COLUNA]["P4"]
                
                        if not "TT_OF" in RELATORIO_DETALHE[TERMINAL]["TOTAL"][DIA_LOGISTICO]:
                            RELATORIO_DETALHE[TERMINAL]["TOTAL"][DIA_LOGISTICO]["TT_OF"] = 0

                        if not "TT_PD" in RELATORIO_DETALHE[TERMINAL]["TOTAL"][DIA_LOGISTICO]:
                            RELATORIO_DETALHE[TERMINAL]["TOTAL"][DIA_LOGISTICO]["TT_PD"] = 0

                        RELATORIO_DETALHE[TERMINAL]["TOTAL"][DIA_LOGISTICO]["TT_OF"] += RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["TT_OF"]
                        RELATORIO_DETALHE[TERMINAL]["TOTAL"][DIA_LOGISTICO]["TT_PD"] += RELATORIO_DETALHE[TERMINAL][FERROVIA][PRODUTO][DIA_LOGISTICO]["TT_PD"] 


    #OBTENDO OS TOTAIS DE GRÃOS (RUMO, MRS E VLI)

    #[RELATORIO] [RUMO] [MRS] [VLI] [RUMO GRAOS]
    
    # TOTAIS = {
    #     "ESQUERDA" : {
    #         "RUMO" : {"GRAOS": 0, "ACUCAR": 0, "CELULOSE": 0, "CONTEINER": 0, "FERTILIZANTES": 0},
    #         "MRS"  : {"GRAOS": 0, "ACUCAR": 0, "CELULOSE": 0, "CONTEINER": 0, "FERTILIZANTES": 0},
    #         "VLI"  : {"GRAOS": 0, "ACUCAR": 0, "CELULOSE": 0, "CONTEINER": 0, "FERTILIZANTES": 0}
    #     },
    #     "DIREITA" : {
    #         "RUMO" : {"GRAOS": 0, "ACUCAR": 0, "CELULOSE": 0, "CONTEINER": 0, "FERTILIZANTES": 0},
    #         "MRS"  : {"GRAOS": 0, "ACUCAR": 0, "CELULOSE": 0, "CONTEINER": 0, "FERTILIZANTES": 0},
    #         "VLI"  : {"GRAOS": 0, "ACUCAR": 0, "CELULOSE": 0, "CONTEINER": 0, "FERTILIZANTES": 0}
    #     }
    # }

    TOTAIS = {}

    




    return RELATORIO_DETALHE 
