# Generated by Django 5.0.2 on 2024-03-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0002_usuario_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
