# Generated by Django 5.0.2 on 2024-08-12 17:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0002_tremvazio_remove_usuario_cargo_restricao_trem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tremvazio',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tremvazio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 12, 17, 13, 34, 810886, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tremvazio',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tremvazio',
            name='partida_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tremvazio',
            name='eot',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Nao')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tremvazio',
            name='margem',
            field=models.CharField(blank=True, choices=[('Direita', 'Direita'), ('Esquerda', 'Esquerda')], max_length=8),
        ),
    ]
