# Generated by Django 5.0.2 on 2024-04-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0002_trem'),
    ]

    operations = [
        migrations.AddField(
            model_name='trem',
            name='ferrovia',
            field=models.CharField(default='RUMO', max_length=50),
            preserve_default=False,
        ),
    ]
