# Generated by Django 5.0.2 on 2024-04-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0003_trem_ferrovia'),
    ]

    operations = [
        migrations.AddField(
            model_name='trem',
            name='posicao_previsao',
            field=models.IntegerField(default=0, verbose_name='Posição de Previsão'),
        ),
        migrations.AlterField(
            model_name='trem',
            name='ferrovia',
            field=models.CharField(choices=[('MRS', 'MRS'), ('RUMO', 'RUMO'), ('VLI', 'VLI')], max_length=50),
        ),
    ]
