# Generated by Django 5.0.2 on 2024-08-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0003_tremvazio_comentario_tremvazio_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trem',
            name='encoste',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trem',
            name='translogic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trem',
            name='previsao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
