# Generated by Django 5.0.2 on 2024-04-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0004_trem_posicao_previsao_alter_trem_ferrovia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=50)),
                ('mercadoria', models.CharField(max_length=50)),
                ('comeca_em', models.DateTimeField()),
                ('termina_em', models.DateTimeField()),
                ('porcentagem', models.IntegerField()),
                ('motivo', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='trem',
            name='posicao_previsao',
            field=models.IntegerField(default=0),
        ),
    ]
