# Generated by Django 5.0.2 on 2024-08-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0004_trem_encoste_trem_translogic_alter_trem_previsao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('margem', models.CharField(max_length=100)),
                ('patio', models.CharField(max_length=100)),
                ('tempo_encoste', models.IntegerField()),
            ],
        ),
    ]
