# Generated by Django 5.0.2 on 2024-05-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0005_restricao_alter_trem_posicao_previsao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to='fotos_de_perfil'),
        ),
    ]
