# Generated by Django 5.0.2 on 2024-08-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0005_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='ordem',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
