# Generated by Django 5.0.2 on 2024-05-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0006_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='anonimo.jpg', upload_to='fotos_de_perfil'),
        ),
    ]
