# Generated by Django 5.0.2 on 2024-08-19 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0006_terminal_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trem',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='previsao_trens.terminal'),
        ),
    ]
