# Generated by Django 5.0.2 on 2024-08-19 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0007_alter_trem_terminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercadorias', to='previsao_trens.segmento')),
            ],
        ),
        migrations.AddField(
            model_name='terminal',
            name='segmento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='terminais', to='previsao_trens.segmento'),
            preserve_default=False,
        ),
    ]
