# Generated by Django 5.0.2 on 2024-06-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0007_alter_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TremVazio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=100)),
                ('ferrovia', models.CharField(choices=[('MRS', 'MRS'), ('RUMO', 'RUMO'), ('VLI', 'VLI')], max_length=50)),
                ('loco_1', models.CharField(max_length=100)),
                ('loco_2', models.CharField(max_length=100)),
                ('loco_3', models.CharField(max_length=100)),
                ('loco_4', models.CharField(max_length=100)),
                ('loco_5', models.CharField(max_length=100)),
                ('previsao', models.DateTimeField()),
                ('eot', models.CharField(max_length=100)),
                ('vagoes', models.IntegerField()),
                ('segmento_01', models.CharField(max_length=50)),
                ('segmento_02', models.CharField(max_length=50)),
                ('segmento_03', models.CharField(max_length=50)),
                ('margem', models.CharField(choices=[('DIREITA', 'DIREITA'), ('ESQUERDA', 'ESQUERDA')], max_length=100)),
            ],
        ),
    ]
