# Generated by Django 5.0.2 on 2024-06-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0008_tremvazio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tremvazio',
            name='loco_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tremvazio',
            name='loco_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tremvazio',
            name='loco_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tremvazio',
            name='loco_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tremvazio',
            name='segmento_02',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tremvazio',
            name='segmento_03',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
