# Generated by Django 5.0.2 on 2024-08-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0008_segmento_mercadoria_terminal_segmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trem',
            name='mercadoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='previsao_trens.mercadoria'),
        ),
    ]
