# Generated by Django 5.0.2 on 2024-06-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0009_alter_tremvazio_loco_2_alter_tremvazio_loco_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tremvazio',
            old_name='vagoes',
            new_name='qt_acuca',
        ),
        migrations.RemoveField(
            model_name='tremvazio',
            name='segmento_01',
        ),
        migrations.RemoveField(
            model_name='tremvazio',
            name='segmento_02',
        ),
        migrations.RemoveField(
            model_name='tremvazio',
            name='segmento_03',
        ),
        migrations.AddField(
            model_name='tremvazio',
            name='qt_celul',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tremvazio',
            name='qt_contei',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tremvazio',
            name='qt_ferti',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tremvazio',
            name='qt_graos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
