# Generated by Django 5.0.2 on 2024-08-28 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0009_alter_trem_mercadoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trem',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trem',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='previsao_trens.terminal'),
        ),
    ]
