# Generated by Django 5.0.2 on 2024-06-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0010_rename_vagoes_tremvazio_qt_acuca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tremvazio',
            name='margem',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tremvazio',
            name='previsao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
