# Generated by Django 5.0.2 on 2024-09-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0010_alter_trem_comentario_alter_trem_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='restricao',
            name='aplicacao_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
