# Generated by Django 5.0.2 on 2024-06-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsao_trens', '0011_alter_tremvazio_margem_alter_tremvazio_previsao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tremvazio',
            name='margem',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tremvazio',
            name='qt_acuca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tremvazio',
            name='qt_celul',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tremvazio',
            name='qt_contei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tremvazio',
            name='qt_ferti',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tremvazio',
            name='qt_graos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
