import pandas as pd


def EDITAR_PARAMETROS(PARAMETROS, ACAO="INSERIR"):

    DIRETORIO = f'previsao_trens/src/PARAMETROS/{PARAMETROS["TABELA"]}'

    DATAFRAME = pd.read_csv(DIRETORIO, sep=";", index_col=0)

    print(f'LINHA: {PARAMETROS["COLUNA"]} COLUNA: {PARAMETROS["COLUNA"]} VALOR: {PARAMETROS["NOVO_VALOR"]}')

    if ACAO == "SOMAR":
        PARAMETROS["NOVO_VALOR"] = DATAFRAME.loc[PARAMETROS["LINHA"], PARAMETROS["COLUNA"]] + int(PARAMETROS["NOVO_VALOR"])

    DATAFRAME.loc[PARAMETROS["LINHA"], PARAMETROS["COLUNA"]] = int(PARAMETROS["NOVO_VALOR"])
    DATAFRAME.loc[PARAMETROS["LINHA"], "TERMINAL"] = DATAFRAME.loc[PARAMETROS['LINHA'], DATAFRAME.columns[1:]].sum()
    DATAFRAME.to_csv(DIRETORIO, sep=";")

    return int(DATAFRAME.loc[PARAMETROS["LINHA"], PARAMETROS["COLUNA"]])